<link href="../../../../application/public/node_modules/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" type="text/css">
<div class="container-fluid">
    <div class="row">
        <nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">
            <div class="position-sticky pt-3">
                <ul class="nav flex-column">
                    <li class="nav-item">
                        <h4>Your Dashboard</h4>
                    </li>
                    <li class="nav-item">
                        <?php echo $this->tag->linkTo(
                            [
                                "application/admin/index",
                                "Orders",
                                "class" => "nav-link"
                            ]
                        ); ?>
                    </li>
                    <li class="nav-item">
                        <?php echo $this->tag->linkTo(
                            [
                                "application/admin/productList",
                                "Products",
                                "class" => "nav-link"
                            ]
                        ); ?>
                    </li>
                </ul>
            </div>
        </nav>